const BLOG_POSTS = [
  {
    id: 1,
    slug: "10-minute-morning-workout",
    title: "The 10-Minute Morning Workout That Changed My Life",
    excerpt: "Start your day with energy and intention. This quick routine fits any schedule and delivers real results.",
    category: "Home Workouts",
    categorySlug: "home-workouts",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-05-28",
    readTime: 5,
    featured: true,
  },
  {
    id: 2,
    slug: "sustainable-weight-loss-guide",
    title: "Sustainable Weight Loss: A Woman's Complete Guide",
    excerpt: "Forget crash diets. Learn the science-backed approach to losing weight while nourishing your body.",
    category: "Weight Loss",
    categorySlug: "weight-loss",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-05-22",
    readTime: 8,
    featured: true,
  },
  {
    id: 3,
    slug: "green-smoothie-bowl-recipe",
    title: "Glow-Boosting Green Smoothie Bowl Recipe",
    excerpt: "Packed with antioxidants and protein, this breakfast bowl keeps you full until lunch.",
    category: "Healthy Recipes",
    categorySlug: "healthy-recipes",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-05-18",
    readTime: 4,
    featured: false,
  },
  {
    id: 4,
    slug: "mindful-movement-anxiety",
    title: "How Mindful Movement Eased My Anxiety",
    excerpt: "Discover the powerful connection between gentle exercise and mental wellness for women.",
    category: "Mental Wellness",
    categorySlug: "mental-wellness",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-05-12",
    readTime: 6,
    featured: false,
  },
  {
    id: 5,
    slug: "daily-motivation-rituals",
    title: "5 Daily Motivation Rituals Every Woman Needs",
    excerpt: "Small habits that build unshakeable confidence and keep you committed to your goals.",
    category: "Motivation",
    categorySlug: "motivation",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-05-05",
    readTime: 5,
    featured: false,
  },
  {
    id: 6,
    slug: "hormone-health-basics",
    title: "Understanding Your Cycle: Hormone Health Basics",
    excerpt: "Learn how to sync your workouts and nutrition with your menstrual cycle for optimal results.",
    category: "Women's Health",
    categorySlug: "womens-health",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-04-28",
    readTime: 7,
    featured: false,
  },
  {
    id: 7,
    slug: "hiit-at-home-no-equipment",
    title: "HIIT at Home: No Equipment Needed",
    excerpt: "Burn calories and build strength with this 20-minute high-intensity interval training session.",
    category: "Home Workouts",
    categorySlug: "home-workouts",
    image: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-04-20",
    readTime: 6,
    featured: false,
  },
  {
    id: 8,
    slug: "meal-prep-sunday-guide",
    title: "Meal Prep Sunday: A Beginner's Guide",
    excerpt: "Save time and eat healthier with these simple meal prep strategies for busy women.",
    category: "Healthy Recipes",
    categorySlug: "healthy-recipes",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-04-15",
    readTime: 9,
    featured: false,
  },
  {
    id: 9,
    slug: "self-compassion-fitness-journey",
    title: "Why Self-Compassion Is Your Secret Fitness Weapon",
    excerpt: "Stop being your harshest critic. Learn to celebrate progress and bounce back from setbacks.",
    category: "Mental Wellness",
    categorySlug: "mental-wellness",
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80",
    author: "Sarah Mitchell",
    date: "2026-04-08",
    readTime: 5,
    featured: false,
  },
];

const CATEGORIES = [
  {
    slug: "weight-loss",
    name: "Weight Loss",
    icon: "⚖️",
    description: "Science-backed strategies for sustainable, healthy weight management.",
    color: "from-blush-400 to-blush-600",
    count: 12,
  },
  {
    slug: "home-workouts",
    name: "Home Workouts",
    icon: "🏠",
    description: "Effective exercises you can do anywhere, no gym required.",
    color: "from-plum-400 to-plum-600",
    count: 18,
  },
  {
    slug: "healthy-recipes",
    name: "Healthy Recipes",
    icon: "🥗",
    description: "Delicious, nutritious meals that support your wellness goals.",
    color: "from-green-400 to-emerald-500",
    count: 24,
  },
  {
    slug: "womens-health",
    name: "Women's Health",
    icon: "💜",
    description: "Expert insights on hormones, cycle syncing, and women's wellness.",
    color: "from-purple-400 to-plum-600",
    count: 15,
  },
  {
    slug: "motivation",
    name: "Motivation",
    icon: "✨",
    description: "Inspiration and mindset tips to keep you moving forward.",
    color: "from-amber-400 to-orange-500",
    count: 20,
  },
  {
    slug: "mental-wellness",
    name: "Mental Wellness",
    icon: "🧘",
    description: "Mindfulness, stress relief, and emotional wellbeing practices.",
    color: "from-sky-400 to-blue-500",
    count: 14,
  },
];

const TESTIMONIALS = [
  {
    name: "Emily R.",
    text: "BloomFit changed how I see fitness. It's not about punishment—it's about loving yourself through movement.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    rating: 5,
  },
  {
    name: "Jessica M.",
    text: "The home workouts are perfect for my busy schedule. I've lost 15 pounds and feel stronger than ever!",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    rating: 5,
  },
  {
    name: "Amanda K.",
    text: "Finally, a wellness blog that speaks to real women. The recipes are amazing and so easy to make.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80",
    rating: 5,
  },
];

const GALLERY_IMAGES = [
  "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80",
  "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&q=80",
  "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80",
  "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80",
  "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80",
  "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400&q=80",
  "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&q=80",
  "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&q=80",
];
